import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';
import { prisma } from '@/lib/prisma';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { ConfirmationEmail } from '@/lib/email-templates/confirmation-email';

const resend = new Resend(process.env.RESEND_API_KEY);

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    const { email, password, name } = await request.json();

    if (!email || !password) {
      return NextResponse.json({ error: 'Email and password are required' }, { status: 400 });
    }

    // Check if user already exists in Prisma database
    const existingUser = await prisma.user.findUnique({
      where: { email: email.toLowerCase() },
    });

    if (existingUser) {
      return NextResponse.json({ error: "Email already registered. Please login instead." }, { status: 400 });
    }

    // Generate link using Admin API (creates the user but prevents Supabase from sending its default email)
    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'signup',
      email,
      password,
      data: { full_name: name || '' }
    });

    if (linkError) {
      if (linkError.message.toLowerCase().includes('already registered')) {
        return NextResponse.json({ error: "Email already registered. Please login instead." }, { status: 400 });
      }
      return NextResponse.json({ error: linkError.message }, { status: 400 });
    }

    // We use the action_link generated by Supabase because it properly verifies the token
    // on the Supabase backend and then redirects to the callback route with the necessary session info.
    let confirmUrl = linkData.properties.action_link;

    // Ensure the redirect_to parameter points to our callback
    const urlObj = new URL(confirmUrl);
    urlObj.searchParams.set('redirect_to', `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/callback`);
    confirmUrl = urlObj.toString();

    const emailHtml = renderToStaticMarkup(
      React.createElement(ConfirmationEmail, {
        name: name || 'there',
        confirmationLink: confirmUrl
      })
    );

    const { data, error } = await resend.emails.send({
      from: 'Sva-Rajya <noreply@update.svarajya.com>', // Update with your verified Resend domain if necessary
      to: email,
      subject: 'Welcome to Sva-Rajya — Confirm Your Kingdom',
      html: emailHtml
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, user: linkData.user });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
