/**
 * Module Configuration — All 21 Rajya modules with metadata
 */

export interface ModuleConfig {
  id: number;
  key: string;
  name: string;
  hindiName: string;
  icon: string;
  route: string;
  color: string;
  description: string;
  chapters: string[];
  isImplemented: boolean;
}

export const MODULES: Record<string, ModuleConfig> = {
  FOUNDATION: {
    id: 1,
    key: 'FOUNDATION',
    name: 'Foundation',
    hindiName: 'Sthapana',
    icon: '👑',
    route: '/foundation',
    color: '#D4AF37',
    description: 'Profile, Family & Education — the bedrock of your Rajya',
    chapters: ['raja-parichay', 'parivar', 'shiksha'],
    isImplemented: true,
  },
  PEHCHAAN: {
    id: 2,
    key: 'PEHCHAAN',
    name: 'Identity Vault',
    hindiName: 'Pehchaan',
    icon: '🔏',
    route: '/pehchaan/records',
    color: '#7B2FBE',
    description: 'All your identity documents — PAN, Aadhaar, Passport and more',
    chapters: ['dastaavet', 'matrika', 'pramaan'],
    isImplemented: true,
  },
  DWAAR: {
    id: 3,
    key: 'DWAAR',
    name: 'Credentials',
    hindiName: 'Dwaar',
    icon: '🗝️',
    route: '/dwaar/portals',
    color: '#C0392B',
    description: 'All your portal logins, passwords and digital credentials',
    chapters: ['kunji', 'darwaza'],
    isImplemented: true,
  },
  KOSH: {
    id: 4,
    key: 'KOSH',
    name: 'Income',
    hindiName: 'Kosh',
    icon: '💰',
    route: '/kosh/sources',
    color: '#27AE60',
    description: 'All your income sources — salary, business, freelance, rental',
    chapters: ['aamdani', 'vipul'],
    isImplemented: true,
  },
  VYAYA: {
    id: 5,
    key: 'VYAYA',
    name: 'Expenses',
    hindiName: 'Vyaya',
    icon: '📊',
    route: '/vyaya/entry',
    color: '#E67E22',
    description: 'Track and categorise all your expenditures',
    chapters: ['kharch', 'budget', 'vishleshana'],
    isImplemented: true,
  },
  KHATE: {
    id: 6,
    key: 'KHATE',
    name: 'Bank Hub',
    hindiName: 'Khate',
    icon: '🏦',
    route: '/khate/accounts',
    color: '#2980B9',
    description: 'All bank accounts, cash flow, and idle funds detection',
    chapters: ['khaata', 'pravah', 'nishkriya'],
    isImplemented: true,
  },
  BEEJ: {
    id: 7,
    key: 'BEEJ',
    name: 'Investments',
    hindiName: 'Beej',
    icon: '🌱',
    route: '/beej',
    color: '#1ABC9C',
    description: 'Mutual funds, stocks, gold, FDs and all investment seeds',
    chapters: ['nivesh', 'vriddhi'],
    isImplemented: false,
  },
  RAKSHA: {
    id: 8,
    key: 'RAKSHA',
    name: 'Insurance',
    hindiName: 'Raksha',
    icon: '🛡️',
    route: '/raksha',
    color: '#8E44AD',
    description: 'Life, health, motor and all your protection shields',
    chapters: ['suraksha', 'kavach'],
    isImplemented: true,
  },
  RIN: {
    id: 9,
    key: 'RIN',
    name: 'Loans',
    hindiName: 'Rin',
    icon: '📋',
    route: '/rin',
    color: '#E74C3C',
    description: 'Home, car, personal loans and EMI management',
    chapters: ['rin-praapt', 'emi'],
    isImplemented: true,
  },
  BHOOMI: {
    id: 10,
    key: 'BHOOMI',
    name: 'Property',
    hindiName: 'Bhoomi',
    icon: '🏠',
    route: '/bhoomi',
    color: '#95A5A6',
    description: 'Real estate, property documents and valuations',
    chapters: ['sampatti', 'mulyankan'],
    isImplemented: false,
  },
  KAR: {
    id: 11,
    key: 'KAR',
    name: 'Tax',
    hindiName: 'Kar',
    icon: '📝',
    route: '/kar',
    color: '#F39C12',
    description: 'ITR filing, Form 16, tax savings and compliance',
    chapters: ['kar-vyavastha', 'bachao'],
    isImplemented: true,
  },
  MITRA: {
    id: 12,
    key: 'MITRA',
    name: 'Nominees & Will',
    hindiName: 'Mitra',
    icon: '🤝',
    route: '/mitra',
    color: '#16A085',
    description: 'Nominees, beneficiary mapping and will preparation',
    chapters: ['uttaradhikari', 'vasiyat'],
    isImplemented: true,
  },
  LEAKAGE: {
    id: 13,
    key: 'LEAKAGE',
    name: 'Subscriptions',
    hindiName: 'Seepage',
    icon: '🕳️',
    route: '/leakage',
    color: '#7F8C8D',
    description: 'Detect and audit all your recurring subscription leakages',
    chapters: ['seepaj', 'audit'],
    isImplemented: true,
  },
  LAKSHYA: {
    id: 14,
    key: 'LAKSHYA',
    name: 'Goals',
    hindiName: 'Lakshya',
    icon: '🎯',
    route: '/lakshya',
    color: '#9B59B6',
    description: 'Financial goals — retirement, education, home, travel',
    chapters: ['uddeshy', 'niyojan'],
    isImplemented: false,
  },
  SAMPATTI: {
    id: 15,
    key: 'SAMPATTI',
    name: 'Asset Inventory',
    hindiName: 'Sampatti',
    icon: '💎',
    route: '/sampatti',
    color: '#F1C40F',
    description: 'All physical assets — jewellery, vehicles, collectibles',
    chapters: ['chatar', 'mulyankan'],
    isImplemented: false,
  },
  GRANTHAGAAR: {
    id: 16,
    key: 'GRANTHAGAAR',
    name: 'Document Vault',
    hindiName: 'Granthagaar',
    icon: '📚',
    route: '/granthagaar',
    color: '#2C3E50',
    description: 'Local-first document storage with cloud backup option',
    chapters: ['dastaavet', 'surakshit'],
    isImplemented: false,
  },
  SUCHAK: {
    id: 17,
    key: 'SUCHAK',
    name: 'Dashboard',
    hindiName: 'Suchak',
    icon: '📉',
    route: '/suchak',
    color: '#2980B9',
    description: 'Your Rajya overview — health score, alerts, net worth',
    chapters: ['pariksha'],
    isImplemented: false,
  },
  DOOT: {
    id: 18,
    key: 'DOOT',
    name: 'Reminders',
    hindiName: 'Doot',
    icon: '🔔',
    route: '/doot',
    color: '#E67E22',
    description: 'Smart reminders for renewals, EMIs, and deadlines',
    chapters: ['sunaai'],
    isImplemented: false,
  },
  MANTRI: {
    id: 19,
    key: 'MANTRI',
    name: 'Insights',
    hindiName: 'Mantri',
    icon: '🏺',
    route: '/mantri',
    color: '#8E44AD',
    description: 'AI-powered insights and financial recommendations',
    chapters: ['gyaan'],
    isImplemented: false,
  },
  SURAKSHA: {
    id: 20,
    key: 'SURAKSHA',
    name: 'Security',
    hindiName: 'Suraksha',
    icon: '🔒',
    route: '/suraksha',
    color: '#C0392B',
    description: 'Two-factor auth, PIN lock, session management',
    chapters: ['niti'],
    isImplemented: false,
  },
  RAJ_MANTRI: {
    id: 21,
    key: 'RAJ_MANTRI',
    name: 'AI Assistant',
    hindiName: 'Raj Mantri',
    icon: '🤖',
    route: '/raj-mantri',
    color: '#1ABC9C',
    description: 'Your personal AI financial advisor — ask anything',
    chapters: ['prashna'],
    isImplemented: false,
  },
};

export const MODULE_ORDER = Object.values(MODULES).sort((a, b) => a.id - b.id);
