import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';
import { getResetPasswordEmailHtml } from '@/lib/email-templates/html-templates';

const resend = new Resend(process.env.RESEND_API_KEY);

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    const { email } = await request.json();

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 });
    }

    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'recovery',
      email,
    });

    if (linkError) {
      return NextResponse.json({ error: linkError.message }, { status: 400 });
    }

    // We use the action_link generated by Supabase.
    // When the user clicks this, Supabase verifies the recovery token and generates
    // the true JWT access_token, then redirects to the callback route:
    let resetUrl = linkData.properties.action_link;

    const urlObj = new URL(resetUrl);
    urlObj.searchParams.set('redirect_to', `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/reset-password`);
    resetUrl = urlObj.toString();

    // If we can't get the name easily from auth admin for reset, we use a fallback
    // Actually, we could fetch from Prisma, but for now fallback to 'User'
    // Since name isn't readily available in generateLink response for recovery
    // Let's see if linkData.user has user_metadata.full_name
    const fullName = linkData.user?.user_metadata?.full_name || 'User';

    const emailHtml = getResetPasswordEmailHtml(fullName, resetUrl);

    const { data, error } = await resend.emails.send({
      from: 'Sva-Rajya <noreply@update.svarajya.com>', // Update with your verified Resend domain if necessary
      to: email,
      subject: 'Sva-Rajya — Password Reset Request',
      html: emailHtml
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
